name: Android CI

on:
  push:
#    branches: [ "master" ]
    paths:
       - 'action.on' # 只有 特定 文件的更改才构建
#
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
#      run: ./gradlew build
      run: ./gradlew   assembleDebug #--debug  #build
#assembleRelease assembleDebug

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
